<?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('auth', array('action' => 'add')));
    echo $this->form()->openTag($form);
?>

<h1>Identifiez-vous</h1>
<?php 

echo $this->form()->openTag($form);
echo $this->formRow($form->get('login'));
echo $this->formElementErrors($form->get('login'));
echo $this->formRow($form->get('pwd'));
 echo $this->formElementErrors($form->get('pwd'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
