<?php

$title = 'Editer Produit';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
/*$form->setAttribute('action', $this->url(
    'produits',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));*/
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('categorie_id'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('info'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();