<?php

$title = 'Editer Produit';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div style="float:left">
    <?php
    $form = $this->form;
    $formUpload = $this->imageUploadForm;
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('name'));
    echo $this->formRow($form->get('categorie_id'));
    echo $this->formRow($form->get('description'));
    echo $this->formRow($form->get('info'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
<div style="float:right">
    <h3>Gestion des images du produit</h3>
    <div id="images">
    
        <?php 
    foreach ($this->imagesProduits as $image) : ?>
    <div class="image-wrapper">
        <img src="<?php echo $this->basePath(). $image->url ?>" width="100px" />
        <div class="delete-image" onclick="deleteImage(<?php echo $image->id ?>)">
            Supprimer
        </div>
    </div>
    <?php endforeach; ?>
        
    </div>
    <div class="clearfix"></div>
    
    <p>Attention : les images doivent être optimisées pour le site avant l'upload.</p>
<?php
    $formUpload->setAttribute(
            'action', 
            $this->url('produits', 
                    array(
                        'action' => 'uploadimage', 
                        'id' => $form->get('id')->getValue()
                        )
                    )
            );
    $formUpload->prepare();
    echo $this->form()->openTag($formUpload);
    echo $this->formHidden($formUpload->get('produit_id'));
    echo $this->formRow($formUpload->get('url'));
    echo $this->formSubmit($formUpload->get('submit'));
    echo $this->form()->closeTag();
?>
</div>
<div class="clearfix"></div>


<script>
    function deleteImage(id)
    {
        $.ajax({
            url: '<?php echo $this->url('produits/', array('action' => 'deleteimage')) ?>',
            data : {
                'id' : id                
            },
            type:'post',
            dataType : 'json',
            success: function(response) 
            {
                $('#images').html('');
                $.each(response.images, function(index, image){
                    $('<div class="image-wrapper">' +
                            '<img src="<?php echo $this->basePath() ?>'+image.url+'" width="100px" />' +
                            '<div class="delete-image" onclick="deleteImage('+image.id+')">' +
                                'Supprimer' +
                            '</div>'+
                        '</div>').appendTo($('#images'));
                });
                
            }
        });
    }
</script>