<?php

$title = 'Produits';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('produits/', array(
        'action'=>'add'));?>">Ajouter un produit</a></p>

<?php if (count($produits)) : ?>

<table class="table">
<tr>
    <th>ID</th>
    <th>Nom</th>
    <th>Description</th>
    <th>&nbsp;</th>
</tr>
<?php 
    foreach($produits as $produit) : ?>
<tr>
    <td><?php echo $produit->id; ?></td>
    <td><?php echo $this->escapeHtml($produit->name);?></td>
    <td><?php echo $produit->description; ?></td>    <td>
        <a href="<?php echo $this->url('produits',
            array('action'=>'edit', 'id' => $produit->id));?>">Modifier</a>
        <a href="<?php echo $this->url('produits',
            array('action'=>'delete', 'id' => $produit->id));?>">Supprimer</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php endif; ?>