<?php

$title = 'Ajouter une nouvelle catégorie';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('parent'));
echo $this->formRow($form->get('lien'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();