<?php

$title = 'Supprimer une catégorie';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Etes-vous certain de vouloir supprimer cette catégorie et toutes ses filles ?
    '<?php echo $this->escapeHtml($categorie->name); ?>'
</p>
<?php
$url = $this->url('categories', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $categorie->id; ?>" />
    <input type="submit" name="del" value="Oui" />
    <input type="submit" name="del" value="Non" />
</div>
</form>