<!DOCTYPE html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
    <title>AGAPE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <link rel="shortcut icon" href="../favicon.ico">
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    
    <script src="js/jquery.js"></script>
</head>

<body>
    <!-- Message Js désactivé -->
    <noscript><div id="nojs">Vous devez activer le Javascript sur votre navigateur pour profiter pleinement de ce site <a href="http://www.maboite.qc.ca/activation_js.php" target="_blank"> En savoir plus ...</a></div></noscript>

    <!-- Home -->
    <div id="home" class="content">
        <div id="column">
            <div id="textwrap">
                <p class="upper space2 size15">Stylisme en agencement & décoration de cuisines.</p><br/>
                <span class="upper bold">AGAPè</span>, c'est le spécialiste de l'aménagement de l'espace cuisine.<br/>
                Que vous souhaitiez une cuisine neuve ou bien rénover votre cuisine actuelle, <span class="upper bold">AGAPè</span> vous propose une offre complète : <span class="ita">produits, matériaux et prestations de mise en oeuvre.</span><br/><br/>
                Votre magasin <span class="upper bold">AGAPè</span> est partenaire de la marque <span class="bold">NEXT</span>, propriété du fabricant allemand <span class="bold">Schuller</span> et des plus grandes marques d'accessoires et d'électroménager. <span class="upper bold">AGAPè</span> est aussi un bureau d'agencement et de création de mobiliers qui peuvent être fabriqués dans nos propres ateliers.<br/><br/>
                <span class="upper bold">AGAPè</span> sélectionne chaque élément de votre future cuisine sur les critères de : <span class="ita">qualité, performance, fonctionnalité, design, écologie....</span><br/><br/>
                Les prestations de mise en oeuvre bénéficient d'une garantie décennale.<br/><br/>
                N'hésitez pas à venir à notre rencontre pour nous expliquer votre projet, nos équipes sont à votre écoute.<br/><br/>
                <span class="encart-devis">DEVIS GRATUIT SUR RENDEZ-VOUS :<br/>
                    05 55 55 94 23</span><br/>
                <span class="size11">Chantiers sur région Limousin , Paris et côte ouest de La Rochelle à Arcachon , autres régions et étranger sur demande.</span>
            </div>
        </div>
        <img id="bg" alt="" src="" />
    </div>
    <!-- /home -->

    <!-- Panel -->
    <div id="panel" class="panel">
        <div class="content">

        </div>
    </div>
    <!-- /Panel -->

    <!-- Mentions légales -->
    <div id="panel6" class="panel">
        <div class="content">
            <div id="columnOpaFloat">
                <div id="textwrapOpaFloat">
                    <span class="upper"><span class="size15 space2">mentions légales</span><br/><br/><br/>

                        <span class="bold">SARL STYLAD</span><br/>
                        Siège social :<br/>
                        47 Avenue Georges Dumas<br/>
                        87000 Limoges<br/>
                        Limousin, France<br/>
                        Tél. : 05 55 55 94 23<br/><br/>

                        R.C.S Limoges 521 271 163<br/>
                        Capital : 10 000 euros<br/>
                        N°Siret : 52127116300029<br/>
                        APE : 7022Z<br/><br/><br/>


                        <span class="bold">Direction de la publication :</span><br/>
                        Gérard Pauliat<br/><br/><br/>

                        <span class="bold">Crédit photos :</span><br/>
                        Schüller, Corian©<br/></span>
                    <span class="ita size11">Tous droits réservés sur les photos et images</span><br/><br/><br/>


                    <span class="upper"><span class="bold">Conception et développement :</span><br/>
                        Stylad<br/><br/><br/>


                        <span class="bold">Hébergement OVH SAS</span><br/>
                        BP 80157 - 59053 Roubaix Cedex 1<br/>
                        Tél. : 0899 701 761<br/>
                        www.ovh.com<br/><br/><br/>


                        <span class="bold">Législation en vigueur</span><br/></span>
                    L'usage de ce site web est régi par la loi française à l'exception de toute autre législation.
                </div>
            </div>
            <div id="columnFloat">
                <div id="textwrapFloat">
                    <span class="upper space2 size15">utilisation</span><br/>

                    L'utilisateur du site Internet <span class="bold">www.agape-cuisines-limoges.com</span> connaît disposer de la compétence et des moyens nécessaires pour accéder et utiliser ce site Internet. Les utilisateurs du site web sont tenus de respecter les dispositions de la loi relative à l'informatique, aux fichiers et aux libertés, dont la violation est passible de sanctions pénales. Ils doivent notamment s'abstenir, s'agissant d'informations nominatives auxquelles ils accèdent, de toute collecte, de toute utilisation détournée et d'une manière générale, de tout acte susceptible de porter atteinte à la vie privée ou à la réputation des personnes.<br/><br/>

                    <span class="upper space2 size15">Contenu du site</span><br/>
                    La société STYLAD met à disposition des utilisateurs du site Internet www.agape-cuisines-limoges.com des informations et outils disponibles et vérifiés, mais elle ne saurait être tenue pour responsable des erreurs ou de l'indisponibilité de certaines informations. Nous remercions les utilisateurs du site Internet de nous faire part d'éventuelles omissions, erreurs ou corrections, en adressant un e-mail au webmaster du site à l'adresse <span class="bold">contact@avaconcept.com</span><br/><br/>

                    <span class="upper space2 size15">Propriété</span><br/>
                    La structure générale, ainsi que les textes, images animées ou fixes, savoir-faire, dessins, graphismes et tous autres éléments composant le site Internet www.agape-cuisines-limoges.com sont de l'utilisation exclusive de la société STYLAD. Toute représentation totale ou partielle de ce site, par quelques procédés que ce soient, sans autorisation expresse de la société STYLAD, est interdite et constituerait une contrefaçon sanctionnée par les articles L335-2 et suivants du Code de la propriété intellectuelle. Les liens hypertextes mis en place dans le cadre du présent site Internet en direction d'autres ressources présentes sur le réseau internet, ne sauraient engager la responsabilité de la société STYLAD. Les utilisateurs et visiteurs du site web ne peuvent mettre en place un hyperlien en direction de ce site sans l'autorisation expresse et préalable de la société STYLAD. Pour cela merci d'adresser un mail à contact@avaconcept.com<br/><br/>
                </div>
            </div>
        </div>
    </div>
    <!-- /Mentions légales -->

    
    <?php
    ///////////// CONTENT
    echo $this->content;
    ?>
    

    <div class="clr"></div>

    <div id="detailNext">
        <div id="colonne_detail">
            <div id="nom_produit"></div><br/>
            <div class="title_next">DESCRIPTION</div>
            <div id="desc_produit"></div><br/>
            <div class="title_next">INFO TECHNIQUE</div>
            <div id="info_produit"></div>
            <div id="ctrl_next">
                <div class="ctrl" id="prev"></div>
                <div class="ctrl" id="next"></div>
                <div class="ctrl" id="close"></div>
            </div>
        </div>
        <div id="image_detail"></div>
    </div>

    <div id="confirmBox">
        <p>Votre message a bien été envoyé</p>
        <input class="closebtn marge1" type="button" onClick="fermerConfirm();" name="closeConfirm" value="OK" />
    </div>

    <div id="alertBox">
        <p>Merci de saisir votre nom, un email valide et un message</p>
        <input class="closebtn marge2" type="button" onClick="fermerAlert();" name="closeAlert" value="OK" />
    </div>

    
    <script src="js/jquery.preloader.js"></script>
    <script src="js/easing.js"></script>
    <script src="js/fonction.js"></script>
</body>
</html>
