<!-- Header  -->

    <div id="header">
        <a id="link-home" href="#"><img id="logo" src="images/logo.png"></a>
        <ul id="navigation">
            <div id="fancy"></div>
        <?php 
        $i = 0;
        foreach ($this->categories as $categorie) : ?>
            <li class="lienmenu <?php echo (count($categorie['children'])) ? 'hasChildren' : ''?>" 
                id="<?php echo $categorie['id'] ?>" name="<?php echo $i ?>"><?php echo $categorie['name'] ?></li>
                
            <?php if (count($categorie['children'])) : ?>
                <ul id="submenu-<?php echo $categorie['id'] ?>" class="menusub">
                    <?php foreach($categorie['children'] as $child) : ?>
                        <li class="lienmenusub" id="<?php echo $child['id'] ?>"><?php echo $child['name'] ?></li>
                    <?php endforeach; ?>
                </ul>
            
            <?php endif; ?>
        <?php
            $i++;
        endforeach; ?>
             <li class="lienmenu" id="link-contact" name="6">contact</li>
        </ul>
        
        
        <div id="social">
            <div id="logowrap">
                <a href="#" id="fb"></a>
                <a href="#" id="twitter"></a>
                <a href="#" id="flickr"></a>
                <div class="clr"></div>
            </div>
            <div>
                <p><input type="button" id="link-mention" value="mentions légales" /></p>
            </div>
        </div>
    </div>
<?php
// Génération des écouteurs sur les catégories ayant des enfants
$script = '';
foreach ($this->categories as $categorie) : 
    if (count($categorie['children'])) : 
$script.=<<<SCRIPT
        $("#$categorie[id]").click(function(){
           if ($(this).hasClass('hasChildren') && !$(this).hasClass('selected')) {
                $(this).addClass('selected')
                $("#submenu-$categorie[id]").slideToggle();
           }
           
           
        });
SCRIPT;
    endif; 
endforeach;


?>

    <script>
        <?php echo $script; ?>
    </script>

            
       